{% set name = "fisspy" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac5f38b2b416c42fbc64bc7230a16b4b3f789db775c3b5acee2c3bd3551d0bf5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - scipy
    - interpolation >=2.2.6
    - astropy-base
    - sunpy
    - numba
    - matplotlib-base
    - ffmpeg
    - pillow
    - numpy
    - statsmodels
    - pyqt >=5,<6
    - beautifulsoup4
    - pandas
    - ipython
    - joblib

test:
  imports:
    - fisspy
    - fisspy.read
    - fisspy.analysis

about:
  home: http://fiss.snu.ac.kr/
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: 'Python analysis tools for GST/FISS'
  dev_url: https://github.com/SNU-sunday/fisspy

extra:
  recipe-maintainers:
    - jhkang0301
