{% set name = "fisspy" %}
{% set version = "1.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 071a69a92e66b1e109f18054e88cc37b4effd0dabf909be61c22cc6d20b37a82

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - scipy
    - interpolation >=2.2.6
    - astropy
    - sunpy
    - numba
    - matplotlib-base
    - ffmpeg
    - pillow
    - numpy
    - statsmodels
    - pyqt
    - beautifulsoup4
    - pandas
    - ipython

test:
  imports:
    - fisspy
    - fisspy.read
    - fisspy.analysis

about:
  home: http://fiss.snu.ac.kr/
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: 'Python analysis tools for GST/FISS'
  dev_url: https://github.com/SNU-sunday/fisspy

extra:
  recipe-maintainers:
    - jhkang0301
