{% set name = "fisspy" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfeac46c3b199f9f099373acc52b4b7a699025d0bb4e87d613f5ddbd7b1db124

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - scipy
    - interpolation
    - astropy
    - sunpy
    - numba
    - matplotlib-base
    - ffmpeg
    - pillow
    - numpy
    - statsmodels
    - pyqt
    - beuatifulsoup4
    - pandas

test:
  imports:
    - fisspy
    - fisspy.read
    - fisspy.analysis

about:
  home: http://fiss.snu.ac.kr/
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: 'Python analysis tools for GST/FISS'
  dev_url: https://github.com/SNU-sunday/fisspy

extra:
  recipe-maintainers:
    - jhkang0301
