{% set name = "fisspy" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81ecdc00cbbb05cf3dd2dbd7ca40dcc07849c0077881dad819349ed3deb13e66

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - scipy
    - interpolation >=2.2.6
    - astropy
    - sunpy
    - numba
    - matplotlib-base
    - ffmpeg
    - pillow
    - numpy
    - statsmodels
    - pyqt
    - beautifulsoup4
    - pandas
    - ipython

test:
  requires:
    - python {{ python_min }}
  imports:
    - fisspy
    - fisspy.read
    - fisspy.analysis

about:
  home: http://fiss.snu.ac.kr/
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: 'Python analysis tools for GST/FISS'
  dev_url: https://github.com/SNU-sunday/fisspy

extra:
  recipe-maintainers:
    - jhkang0301
