travis:
  secure:
    BINSTAR_TOKEN: jWg4cp6XRKWhTMUp8C9aiAq0kQsivcifQ3sP1iZyc4t7uBbg6NGedzDlbTbkBmf57ZljfXv9kJy358dgxNccjyExfjgy2kMbQgdOYj6RDSOlizuyZF8kQQ+9VKP/wJPh42oxtt04rCmUEvBf/Oyor80uOogq/KfZQySdwmFHJRVD8lj2pVlzAXJK24DEDc+f6prq6pCFP8gM4Svdm6MlZRJtpi08ArvNevguPEOlgUtBqubOXnRd6v84IXwTT/e9f9chtVGgMqEl0kRjMf7+a2Io/f63gvthNXNNEGtD1HHWEY+E5zvQE4JP85sosB0jRc73H16P5FRgGKYGI5h3UNmisJE6cGuy6bqH/2IvKT73nwkduvdUk0b1829+SV9UdcB3/hS5G+VOk7Q/EaIyQw9L1Dgvlz+b/r4SxV1F9I0/SYMMI4Rn/te3P4N6xqe5kRzjBsva2kZzE8PH+l6YsnEsy2ym3nzeyMnVkXgwla60zJMJf4BngMu6g9BQuxZA+Chlal5ciHRTcKD+Ou8mIb5W9b0eceBcK/HrHy2dyeFVJApfbGDe9St6IkPzN6+WBwez7yRaIAD2Q3U/Xazej2sbts08m7w6BBkV/F2x1wHbyKs8HXjW7WXubHamMQaewkX6zfgnxm/oUZ8sTUFMDch3li6sBVE8v7DdlDozrb8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
